data = [
	{
		front: 'WHAT IS THE CAPITAL OF ALABAMA?',
		list1: 'BIRMINGHAM',
		list2: 'HUNTSVILLE',
		list3: 'MONTGOMERY',
		back: 'MONTGOMERY',
	},

	{
		front: 'WHAT IS THE CAPITAL OF ALASKA?',
		list1: 'ANCHORAGE',
		list2: 'FAIRBANKS',
		list3: 'JUNEAU',
		back: 'JUNEAU',
	},
	{
		front: 'WHAT IS THE CAPITAL OF ARIZONA?',
		list1: 'PHOENIX',
		list2: 'TUCSON',
		list3: 'MESA',
		back: 'PHOENIX',
	},
	{
		front: 'WHAT IS THE CAPITAL OF ARKANSAS?',
		list1: 'LITTLE ROCK?',
		list2: 'FAYETTEVILLE',
		list3: 'FORT SMITH',
		back: 'LITTLE ROCK',
	},
	{
		front: 'WHAT IS THE CAPITAL OF CALIFORNIA?',
		list1: 'LOS ANGELES',
		list2: 'SAN DIEGO',
		list3: 'SACRAMENTO',
		back: 'SACRAMENTO',
	},
	{
		front: 'WHAT IS THE CAPITAL OF COLORADO?',
		list1: 'DENVER',
		list2: 'COLORADO',
		list3: 'SPRINGS',
		back: 'DENVER',
	},
	{
		front: 'WHAT IS THE CAPITAL OF CONNECTICUT?',
		list1: 'BRIDGEPORT',
		list2: 'HARTFORD',
		list3: 'NEW HAVEN',
		back: 'HARTFORD',
	},
	{
		front: 'WHAT IS THE CAPITAL OF DELAWARE?',
		list1: 'WILMINGTON',
		list2: 'DOVER',
		list3: 'NEWARK',
		back: 'DOVER',
	},
	{
		front: 'WHAT IS THE CAPITAL OF FLORIDA?',
		list1: 'MIAMI',
		list2: 'TALLAHASSEE',
		list3: 'TAMPA',
		back: 'TALLAHASSEE',
	},
	{
		front: 'WHAT IS THE CAPITAL OF GEORGIA?',
		list1: 'ATLANTA',
		list2: 'AUGUSTA',
		list3: 'COLUMBUS',
		back: 'ATLANTA',
	},
	{
		front: 'WHAT IS THE CAPITAL OF HAWAII?',
		list1: 'PEARL CITY',
		list2: 'HONOLULU',
		list3: 'HILO',
		back: 'HONOLULU',
	},
	{
		front: 'WHAT IS THE CAPITAL OF IDAHO?',
		list1: 'BOISE',
		list2: 'IDAHO FALLS',
		list3: 'MERIDAN',
		back: 'BOISE',
	},
	{
		front: 'WHAT IS THE CAPITAL OF ILLINOIS?',
		list1: 'JOLIET',
		list2: 'ROCKFORD',
		list3: 'SPRINGFIELD',
		back: 'SPRINGFIELD',
	},
	{
		front: 'WHAT IS THE CAPITAL OF INDIANA?',
		list1: 'FORT WAYNE',
		list2: 'INDIANAPOLIS',
		list3: 'SOUTH BEND',
		back: 'INDIANAPOLIS',
	},
	{
		front: 'WHAT IS THE CAPITAL OF IOWA?',
		list1: 'DES MOINE',
		list2: 'CEDAR RAPIDS',
		list3: 'IOWA CITY',
		back: 'DES MOINE',
	},
	{
		front: 'WHAT IS THE CAPITAL OF KANSAS?',
		list1: 'WITCHITA',
		list2: 'KANSAS CITY',
		list3: 'TOPEKA',
		back: 'TOPEKA',
	},
	{
		front: 'WHAT IS THE CAPITAL OF KENTUCKY?',
		list1: 'LOUISVILLE',
		list2: 'FRANKFORT',
		list3: 'LEXINGTON',
		back: 'FRANKFORT',
	},
	{
		front: 'WHAT IS THE CAPITAL OF LOUISIANA?',
		list1: 'NEW ORLEANS',
		list2: 'BATON ROUGE',
		list3: 'LAFAYETTE',
		back: 'BATON ROUGE',
	},
	{
		front: 'WHAT IS THE CAPITAL OF MAINE?',
		list1: 'AUGUSTA',
		list2: 'PORTLAND',
		list3: 'LEWISTON',
		back: 'AUGUSTA',
	},
	{
		front: 'WHAT IS THE CAPITAL OF MARYLAND?',
		list1: 'BALTIMORE',
		list2: 'COLUMBIA',
		list3: 'ANNAPOLIS',
		back: 'ANNAPOLIS',
	},
	{
		front: 'WHAT IS THE CAPITAL OF MASSACHUSETTS?',
		list1: 'BOSTON',
		list2: 'CAMBRIDGE',
		list3: 'WORCESTER',
		back: 'BOSTON',
	},
	{
		front: 'WAHT IS THE CAPITAL OF MICHIGAN?',
		list1: 'DETROIT',
		list2: 'GRAND RAPIDS',
		list3: 'LANSING',
		back: 'LANSING',
	},
	{
		front: 'WHAT IS THE CAPITAL OF MINNESOTA?',
		list1: 'ST. PAUL',
		list2: 'MINNEAPOLIS',
		list3: 'ROCHESTER',
		back: 'ST. PAUL',
	},
	{
		front: 'WHAT IS THE CAPITAL OF MISSISSIPPI?',
		list1: 'JACKSON',
		list2: 'GULFPORT',
		list3: 'SOUTHAVEN',
		back: 'JACKSON',
	},
	{
		front: 'WHAT IS THE CAPITAL OF MISSOURI?',
		list1: 'KANSAS CITY',
		list2: 'ST. LOUIS',
		list3: 'JEFFERSON CITY',
		back: 'JEFFERSON CITY',
	},
	{
		front: 'WHAT IS THE CAPITAL OF MONTANA?',
		list1: 'HELENA',
		list2: 'BILLINGS',
		list3: 'GREAT FALLS',
		back: 'HELENA',
	},
	{
		front: 'WHAT IS THE CAPITAL OF NEBRASKA?',
		list1: 'OMAHA',
		list2: 'LINCOLN',
		list3: 'BELLEVUE',
		back: 'LINCOLN',
	},
	{
		front: 'WHAT IS THE CAPITAL OF NEVADA?',
		list1: 'RENO',
		list2: 'LAS VEGAS',
		list3: 'CARSON CITY',
		back: 'CARSON CITY',
	},
	{
		front: 'WHAT IS THE CAPITAL OF NEW HAMPSHIRE?',
		list1: 'MANCHESTER',
		list2: 'NASHUA',
		list3: 'CONCORD',
		back: 'CONCORD',
	},
	{
		front: 'WHAT IS THE CAPITAL OF NEW JERSEY?',
		list1: 'TRENTON',
		list2: 'NEWARK',
		list3: 'JERSEY CITY',
		back: 'TRENTON',
	},
	{
		front: 'WHAT IS THE CAPITAL OF NEW MEXICO',
		list1: 'ALBUQUERQUE',
		list2: 'SANTA FE',
		list3: 'LAS CRUCES',
		back: 'SANTA FE',
	},
	{
		front: 'WHAT IS THE CAPITAL OF NEW YORK?',
		list1: 'BUFFALO',
		list2: 'ALBANY',
		list3: 'SYRACUSE',
		back: 'ALBANY',
	},
	{
		front: 'WHAT IS THE CAPITAL OF NORTH CAROLINA?',
		list1: 'RALEIGH',
		list2: 'CHARLOTTE',
		list3: 'DURHAM',
		back: 'RALEIGH',
	},
	{
		front: 'WHAT IS THE CAPITAL OF NORTH DAKOTA?',
		list1: 'FARGO',
		list2: 'BISMARCK',
		list3: 'WEST FARGO',
		back: 'BISMARCK',
	},
	{
		front: 'WHAT IS THE CAPITAL OF OHIO',
		list1: 'COLOMBUS',
		list2: 'CLEVELAND',
		list3: 'TOLEDO',
		back: 'COLOMBUS',
	},
	{
		front: 'WHAT IS THE CAPITAL OF OKLAHOMA?',
		list1: 'OKLAHOMA CITY',
		list2: 'TULSA',
		list3: 'NORMAN',
		back: 'OKLAHOMA CITY',
	},
	{
		front: 'WHAT IS THE CAPITAL OF OREGON?',
		list1: 'SALEM',
		list2: 'PORTLAND',
		list3: 'HILLSBORO',
		back: 'SALEM',
	},
	{
		front: 'WHAT IS THE CAPITAL OF PENNSYLVANIA?',
		list1: 'PHILADELPHIA',
		list2: 'PITTSBURGH',
		list3: 'HARRISBURG',
		back: 'HARRISBURG',
	},
	{
		front: 'WHAT IS THE CAPITAL OF RHODE ISLAND?',
		list1: 'CRANSTON',
		list2: 'PROVIDENCE',
		list3: 'WARWICK',
		back: 'PROVIDENCE',
	},
	{
		front: 'WHAT IS THE CAPITAL OF SOUTH CAROLINA?',
		list1: 'COLUMBIA',
		list2: 'CHALESTON',
		list3: 'NORTH CHARLESTON',
		back: 'COLUMBIA',
	},
	{
		front: 'WHAT IS THE CAPITAL OF SOUTH DAKOTA?',
		list1: 'SIOUX FALLS',
		list2: 'RAPID CITY',
		list3: 'PIERRE',
		back: 'PIERRE',
	},
	{
		front: 'WHAT IS THE CAPITAL OF TENNESSEE?',
		list1: 'NASHVILLE',
		list2: 'MEMPHIS',
		list3: 'KNOXVILLE',
		back: 'NASHVILLE',
	},
	{
		front: 'WHAT IS THE CAPITAL OF TEXAS?',
		list1: 'AUSTIN',
		list2: 'HOUSTON',
		list3: 'DALLAS',
		back: 'AUSTIN',
	},
	{
		front: 'WHAT IS THE CAPITAL OF UTAH?',
		list1: 'SALT LAKE CITY',
		list2: 'WEST VALLEY CITY',
		list3: 'PROVO',
		back: 'SALT LAKE CITY',
	},
	{
		front: 'WHAT IS THE CAPITAL OF VERMONT?',
		list1: 'BURLINGTON',
		list2: 'MONTPELIER',
		list3: 'RUTLAND',
		back: 'MONTPELIER',
	},
	{
		front: 'WHAT IS THE CAPITAL OF VIRGINIA?',
		list1: 'RICHMOND',
		list2: 'NORFOLK',
		list3: 'VIRGINIA BEACH',
		back: 'RICHMOND',
	},
	{
		front: 'WHAT IS THE CAPITAL OF WASHINGTON?',
		list1: 'OLYMPIA',
		list2: 'SEATTLE',
		list3: 'TACOMA',
		back: 'OLYMPIA',
	},
	{
		front: 'WHAT IS THE CAPITAL OF WEST VIRGINIA?',
		list1: 'CHARLESTON',
		list2: 'HUNTINGTON',
		list3: 'MORGANTOWN',
		back: 'CHARLESTON',
	},
	{
		front: 'WHAT IS THE CAPITAL OF WISCONSIN?',
		list1: 'MILWAUKEE',
		list2: 'MADISON',
		list3: 'GREEN BAY',
		back: 'MADISON',
	},
	{
		front: 'WHAT IS THE CAPITAL OF WYOMING?',
		list1: 'CASPER',
		list2: 'CHEYENNE',
		list3: 'LARAMIE',
		back: 'CHEYENNE',
	},
];
