data = [
	{
		question: 'WHAT IS THE CAPITAL OF ALABAMA?',
		choice1: 'BIRMINGHAM',
		choice2: 'HUNTSVILLE',
		choice3: 'MONTGOMERY',
		answer: 'MONTGOMERY',
	},

	{
		question: 'WHAT IS THE CAPITAL OF ALASKA?',
		choice1: 'ANCHORAGE',
		choice2: 'FAIRBANKS',
		choice3: 'JUNEAU',
		answer: 'JUNEAU',
	},
	{
		question: 'WHAT IS THE CAPITAL OF ARIZONA?',
		choice1: 'PHOENIX',
		choice2: 'TUCSON',
		choice3: 'MESA',
		answer: 'PHOENIX',
	},
	{
		question: 'WHAT IS THE CAPITAL OF ARKANSAS?',
		choice1: 'LITTLE ROCK?',
		choice2: 'FAYETTEVILLE',
		choice3: 'FORT SMITH',
		answer: 'LITTLE ROCK',
	},
	{
		question: 'WHAT IS THE CAPITAL OF CALIFORNIA?',
		choice1: 'LOS ANGELES',
		choice2: 'SAN DIEGO',
		choice3: 'SACRAMENTO',
		answer: 'SACRAMENTO',
	},
	{
		question: 'WHAT IS THE CAPITAL OF COLORADO?',
		choice1: 'DENVER',
		choice2: 'COLORADO',
		choice3: 'SPRINGS',
		answer: 'DENVER',
	},
	{
		question: 'WHAT IS THE CAPITAL OF CONNECTICUT?',
		choice1: 'BRIDGEPORT',
		choice2: 'HARTFORD',
		choice3: 'NEW HAVEN',
		answer: 'HARTFORD',
	},
	{
		question: 'WHAT IS THE CAPITAL OF DELAWARE?',
		choice1: 'WILMINGTON',
		choice2: 'DOVER',
		choice3: 'NEWARK',
		answer: 'DOVER',
	},
	{
		question: 'WHAT IS THE CAPITAL OF FLORIDA?',
		choice1: 'MIAMI',
		choice2: 'TALLAHASSEE',
		choice3: 'TAMPA',
		answer: 'TALLAHASSEE',
	},
	{
		question: 'WHAT IS THE CAPITAL OF GEORGIA?',
		choice1: 'ATLANTA',
		choice2: 'AUGUSTA',
		choice3: 'COLUMBUS',
		answer: 'ATLANTA',
	},
	{
		question: 'WHAT IS THE CAPITAL OF HAWAII?',
		choice1: 'PEARL CITY',
		choice2: 'HONOLULU',
		choice3: 'HILO',
		answer: 'HONOLULU',
	},
	{
		question: 'WHAT IS THE CAPITAL OF IDAHO?',
		choice1: 'BOISE',
		choice2: 'IDAHO FALLS',
		choice3: 'MERIDAN',
		answer: 'BOISE',
	},
	{
		question: 'WHAT IS THE CAPITAL OF ILLINOIS?',
		choice1: 'JOLIET',
		choice2: 'ROCKFORD',
		choice3: 'SPRINGFIELD',
		answer: 'SPRINGFIELD',
	},
	{
		question: 'WHAT IS THE CAPITAL OF INDIANA?',
		choice1: 'FORT WAYNE',
		choice2: 'INDIANAPOLIS',
		choice3: 'SOUTH BEND',
		answer: 'INDIANAPOLIS',
	},
	{
		question: 'WHAT IS THE CAPITAL OF IOWA?',
		choice1: 'DES MOINE',
		choice2: 'CEDAR RAPIDS',
		choice3: 'IOWA CITY',
		answer: 'DES MOINES',
	},
	{
		question: 'WHAT IS THE CAPITAL OF KANSAS?',
		choice1: 'WITCHITA',
		choice2: 'KANSAS CITY',
		choice3: 'TOPEKA',
		answer: 'TOPEKA',
	},
	{
		question: 'WHAT IS THE CAPITAL OF KENTUCKY?',
		choice1: 'LOUISVILLE',
		choice2: 'FRANKFORT',
		choice3: 'LEXINGTON',
		answer: 'FRANKFORT',
	},
	{
		question: 'WHAT IS THE CAPITAL OF LOUISIANA?',
		choice1: 'NEW ORLEANS',
		choice2: 'BATON ROUGE',
		choice3: 'LAFAYETTE',
		answer: 'BATON ROUGE',
	},
	{
		question: 'WHAT IS THE CAPITAL OF MAINE?',
		choice1: 'AUGUSTA',
		choice2: 'PORTLAND',
		choice3: 'LEWISTON',
		answer: 'AUGUSTA',
	},
	{
		question: 'WHAT IS THE CAPITAL OF MARYLAND?',
		choice1: 'BALTIMORE',
		choice2: 'COLUMBIA',
		choice3: 'ANNAPOLIS',
		answer: 'ANNAPOLIS',
	},
	{
		question: 'WHAT IS THE CAPITAL OF MASSACHUSETTS?',
		choice1: 'BOSTON',
		choice2: 'CAMBRIDGE',
		choice3: 'WORCESTER',
		answer: 'BOSTON',
	},
	{
		question: 'WAHT IS THE CAPITAL OF MICHIGAN?',
		choice1: 'DETROIT',
		choice2: 'GRAND RAPIDS',
		choice3: 'LANSING',
		answer: 'LANSING',
	},
	{
		question: 'WHAT IS THE CAPITAL OF MINNESOTA?',
		choice1: 'ST. PAUL',
		choice2: 'MINNEAPOLIS',
		choice3: 'ROCHESTER',
		answer: 'ST. PAUL',
	},
	{
		question: 'WHAT IS THE CAPITAL OF MISSISSIPPI?',
		choice1: 'JACKSON',
		choice2: 'GULFPORT',
		choice3: 'SOUTHAVEN',
		answer: 'JACKSON',
	},
	{
		question: 'WHAT IS THE CAPITAL OF MISSOURI?',
		choice1: 'KANSAS CITY',
		choice2: 'ST. LOUIS',
		choice3: 'JEFFERSON CITY',
		answer: 'JEFFERSON CITY',
	},
	{
		question: 'WHAT IS THE CAPITAL OF MONTANA?',
		choice1: 'HELENA',
		choice2: 'BILLINGS',
		choice3: 'GREAT FALLS',
		answer: 'HELENA',
	},
	{
		question: 'WHAT IS THE CAPITAL OF NEBRASKA?',
		choice1: 'OMAHA',
		choice2: 'LINCOLN',
		choice3: 'BELLEVUE',
		answer: 'LINCOLN',
	},
	{
		question: 'WHAT IS THE CAPITAL OF NEVADA?',
		choice1: 'RENO',
		choice2: 'LAS VEGAS',
		choice3: 'CARSON CITY',
		answer: 'CARSON CITY',
	},
	{
		question: 'WHAT IS THE CAPITAL OF NEW HAMPSHIRE?',
		choice1: 'MANCHESTER',
		choice2: 'NASHUA',
		choice3: 'CONCORD',
		answer: 'CONCORD',
	},
	{
		question: 'WHAT IS THE CAPITAL OF NEW JERSEY?',
		choice1: 'TRENTON',
		choice2: 'NEWARK',
		choice3: 'JERSEY CITY',
		answer: 'TRENTON',
	},
	{
		question: 'WHAT IS THE CAPITAL OF NEW MEXICO',
		choice1: 'ALBUQUERQUE',
		choice2: 'SANTA FE',
		choice3: 'LAS CRUCES',
		answer: 'SANTA FE',
	},
	{
		question: 'WHAT IS THE CAPITAL OF NEW YORK?',
		choice1: 'BUFFALO',
		choice2: 'ALBANY',
		choice3: 'SYRACUSE',
		answer: 'ALBANY',
	},
	{
		question: 'WHAT IS THE CAPITAL OF NORTH CAROLINA?',
		choice1: 'RALEIGH',
		choice2: 'CHARLOTTE',
		choice3: 'DURHAM',
		answer: 'RALEIGH',
	},
	{
		question: 'WHAT IS THE CAPITAL OF NORTH DAKOTA?',
		choice1: 'FARGO',
		choice2: 'BISMARCK',
		choice3: 'WEST FARGO',
		answer: 'BISMARCK',
	},
	{
		question: 'WHAT IS THE CAPITAL OF OHIO',
		choice1: 'COLOMBUS',
		choice2: 'CLEVELAND',
		choice3: 'TOLEDO',
		answer: 'COLOMBUS',
	},
	{
		question: 'WHAT IS THE CAPITAL OF OKLAHOMA?',
		choice1: 'OKLAHOMA CITY',
		choice2: 'TULSA',
		choice3: 'NORMAN',
		answer: 'OKLAHOMA CITY',
	},
	{
		question: 'WHAT IS THE CAPITAL OF OREGON?',
		choice1: 'SALEM',
		choice2: 'PORTLAND',
		choice3: 'HILLSBORO',
		answer: 'SALEM',
	},
	{
		question: 'WHAT IS THE CAPITAL OF PENNSYLVANIA?',
		choice1: 'PHILADELPHIA',
		choice2: 'PITTSBURGH',
		choice3: 'HARRISBURG',
		answer: 'HARRISBURG',
	},
	{
		question: 'WHAT IS THE CAPITAL OF RHODE ISLAND?',
		choice1: 'CRANSTON',
		choice2: 'PROVIDENCE',
		choice3: 'WARWICK',
		answer: 'PROVIDENCE',
	},
	{
		question: 'WHAT IS THE CAPITAL OF SOUTH CAROLINA?',
		choice1: 'COLUMBIA',
		choice2: 'CHALESTON',
		choice3: 'NORTH CHARLESTON',
		answer: 'COLUMBIA',
	},
	{
		question: 'WHAT IS THE CAPITAL OF SOUTH DAKOTA?',
		choice1: 'SIOUX FALLS',
		choice2: 'RAPID CITY',
		choice3: 'PIERRE',
		answer: 'PIERRE',
	},
	{
		question: 'WHAT IS THE CAPITAL OF TENNESSEE?',
		choice1: 'NASHVILLE',
		choice2: 'MEMPHIS',
		choice3: 'KNOXVILLE',
		answer: 'NASHVILLE',
	},
	{
		question: 'WHAT IS THE CAPITAL OF TEXAS?',
		choice1: 'AUSTIN',
		choice2: 'HOUSTON',
		choice3: 'DALLAS',
		answer: 'AUSTIN',
	},
	{
		question: 'WHAT IS THE CAPITAL OF UTAH?',
		choice1: 'SALT LAKE CITY',
		choice2: 'WEST VALLEY CITY',
		choice3: 'PROVO',
		answer: 'SALT LAKE CITY',
	},
	{
		question: 'WHAT IS THE CAPITAL OF VERMONT?',
		choice1: 'BURLINGTON',
		choice2: 'MONTPELIER',
		choice3: 'RUTLAND',
		answer: 'MONTPELIER',
	},
	{
		question: 'WHAT IS THE CAPITAL OF VIRGINIA?',
		choice1: 'RICHMOND',
		choice2: 'NORFOLK',
		choice3: 'VIRGINIA BEACH',
		answer: 'RICHMOND',
	},
	{
		question: 'WHAT IS THE CAPITAL OF WASHINGTON?',
		choice1: 'OLYMPIA',
		choice2: 'SEATTLE',
		choice3: 'TACOMA',
		answer: 'OLYMPIA',
	},
	{
		question: 'WHAT IS THE CAPITAL OF WEST VIRGINIA?',
		choice1: 'CHARLESTON',
		choice2: 'HUNTINGTON',
		choice3: 'MORGANTOWN',
		answer: 'CHARLESTON',
	},
	{
		question: 'WHAT IS THE CAPITAL OF WISCONSIN?',
		choice1: 'MILWAUKEE',
		choice2: 'MADISON',
		choice3: 'GREEN BAY',
		answer: 'MADISON',
	},
	{
		question: 'WHAT IS THE CAPITAL OF WYOMING?',
		choice1: 'CASPER',
		choice2: 'CHEYENNE',
		choice3: 'LARAMIE',
		answer: 'CHEYENNE',
	},
];
